#!/usr/bin/env bun
/**
 * Scans apps/web/dist and generates a TypeScript module that embeds all
 * static assets as base64-encoded buffers.  The generated file is consumed
 * by the server at compile time so `bun build --compile` bakes the bytes
 * into the single-file binary.
 */
import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, relative, extname } from "node:path";

const WEB_DIST = join(import.meta.dirname, "..", "apps", "web", "dist");
const OUT_FILE = join(
  import.meta.dirname,
  "..",
  "apps",
  "server",
  "src",
  "embedded-assets.generated.ts",
);

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
};

async function walk(dir) {
  const entries = [];
  for (const dirent of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, dirent.name);
    if (dirent.isDirectory()) {
      entries.push(...(await walk(full)));
    } else if (dirent.isFile()) {
      entries.push(full);
    }
  }
  return entries;
}

async function main() {
  let files;
  try {
    await stat(WEB_DIST);
    files = await walk(WEB_DIST);
  } catch {
    console.error(`[embed-assets] ${WEB_DIST} not found — run web build first`);
    process.exit(1);
  }

  if (files.length === 0) {
    console.error(`[embed-assets] ${WEB_DIST} is empty`);
    process.exit(1);
  }

  const lines = [
    "// Auto-generated by scripts/embed-assets.mjs — do not edit",
    "",
    "export interface EmbeddedAsset {",
    "  contentType: string;",
    "  data: Uint8Array;",
    "}",
    "",
    "function b64(s: string): Uint8Array {",
    '  if (typeof Buffer !== "undefined") return Buffer.from(s, "base64");',
    "  const bin = atob(s);",
    "  const bytes = new Uint8Array(bin.length);",
    "  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
    "  return bytes;",
    "}",
    "",
    "export const EMBEDDED_ASSETS: Record<string, EmbeddedAsset> = {",
  ];

  let totalSize = 0;

  for (const file of files.sort()) {
    const rel = "/" + relative(WEB_DIST, file).replace(/\\/g, "/");
    const ext = extname(file).toLowerCase();
    const contentType = MIME_TYPES[ext] ?? "application/octet-stream";
    const buf = await readFile(file);
    const b64 = buf.toString("base64");
    totalSize += buf.length;

    lines.push(`  ${JSON.stringify(rel)}: {`);
    lines.push(`    contentType: ${JSON.stringify(contentType)},`);
    lines.push(`    data: b64(${JSON.stringify(b64)}),`);
    lines.push("  },");
  }

  lines.push("};");
  lines.push("");

  await writeFile(OUT_FILE, lines.join("\n"));
  console.log(
    `[embed-assets] Embedded ${files.length} files (${(totalSize / 1024).toFixed(1)} KB) → ${relative(process.cwd(), OUT_FILE)}`,
  );
}

main();
